name: untitled
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies: # ★ここからすべてのパッケージを正しくインデントして記述★
  flutter:
    sdk: flutter
  flutter_localizations: # flutter_localizations もここに記述
    sdk: flutter
  intl: ^0.20.2 # ★ここを ^0.18.0 から ^0.20.2 に修正★

  cupertino_icons: ^1.0.2
  google_mobile_ads: ^5.1.0
  change_app_package_name: ^1.1.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.1.1
  firebase_storage: ^12.4.6
  image_picker: ^1.1.0
  uuid: ^4.4.0
  cloud_functions: ^5.5.1 # ★正しくインデントしてここに移動★
  just_audio: ^0.9.36   # ★正しくインデントしてここに移動★


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

# The following section is specific to Flutter packages.
flutter: # ★flutterに関する設定は、ファイル内でこの一箇所のみに記述★
  generate: true # ★この設定は 'flutter:' の直下に記述★
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/ # ★忘れずにこの行も維持★
  # ... (他のflutter設定) ...

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/images/launcher/icon_adaptive_foreground.png"