name: untitled
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+70

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 多言語対応
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  google_mobile_ads: ^5.1.0
  change_app_package_name: ^1.1.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.1.1
  uuid: ^4.4.0
  cloud_functions: ^5.5.1
  just_audio: ^0.9.36
  url_launcher: ^6.3.0  # Buy Me a Coffee のリンクを開くために追加
  shared_preferences: ^2.3.2  # コイン/実績/デイリー等のローカル保存
  confetti: ^0.8.0  # 勝利演出の紙吹雪
  flutter_svg: ^2.0.10  # 応援キャラのイラスト表示


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

# The following section is specific to Flutter packages.
flutter:
  generate: true # 多言語ファイルの自動生成
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/supporters/
    - assets/audio/
  # ... (他のflutter設定) ...

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/images/launcher/icon_adaptive_foreground.png"
