// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDI6L63rFi5sWPv_q0q-JU4jJEnbRoukw',
    appId: '1:255569645888:web:571971b50dc7c4af5daaa5',
    messagingSenderId: '255569645888',
    projectId: 'nanimonjya',
    authDomain: 'nanimonjya.firebaseapp.com',
    storageBucket: 'nanimonjya.firebasestorage.app',
    measurementId: 'G-FN6NJBFD2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vyg42Esz8zm16DuG3DJWDWFGZ_VlwnE',
    appId: '1:255569645888:android:ccb5680cd9de5a615daaa5',
    messagingSenderId: '255569645888',
    projectId: 'nanimonjya',
    storageBucket: 'nanimonjya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPDPAAQUhFQFE_wuRRNEL-4My0KYTP6Y',
    appId: '1:255569645888:ios:244ac4db781e5a115daaa5',
    messagingSenderId: '255569645888',
    projectId: 'nanimonjya',
    storageBucket: 'nanimonjya.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPDPAAQUhFQFE_wuRRNEL-4My0KYTP6Y',
    appId: '1:255569645888:ios:244ac4db781e5a115daaa5',
    messagingSenderId: '255569645888',
    projectId: 'nanimonjya',
    storageBucket: 'nanimonjya.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDI6L63rFi5sWPv_q0q-JU4jJEnbRoukw',
    appId: '1:255569645888:web:ef4ff391970b95675daaa5',
    messagingSenderId: '255569645888',
    projectId: 'nanimonjya',
    authDomain: 'nanimonjya.firebaseapp.com',
    storageBucket: 'nanimonjya.firebasestorage.app',
    measurementId: 'G-WSW7NGL4X6',
  );

}